-- AlterTable
ALTER TABLE "Purchase" ADD COLUMN "feeTotalUsd" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Purchase" ADD COLUMN "feeTreasuryUsd" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Purchase" ADD COLUMN "feeOperatorUsd" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Purchase" ADD COLUMN "sellerNetUsd" DOUBLE PRECISION NOT NULL DEFAULT 0;
