import type { Metadata } from "next";
import localFont from "next/font/local";
import Link from "next/link";
import Script from "next/script";
import { BrandMark } from "@/components/MintLeaf";
import { LogoIntroSplash } from "@/components/LogoIntroSplashLoader";
import { PageEngraveBackground } from "@/components/PageEngraveBackground";
import { ReplayIntroButton } from "@/components/ReplayIntroButton";
import { DiscoverySidebar } from "@/components/DiscoverySidebar";
import { SiteNav } from "@/components/SiteNav";
import { ThemeToggle } from "@/components/ThemeToggle";
import { getSessionUser, publicSession } from "@/lib/auth/session";
import { appBaseUrl } from "@/lib/auth/paths";
import { rootSiteMetadata, siteJsonLdGraph } from "@/lib/seo/site";
import { THEME_BOOT_SCRIPT } from "@/lib/theme";
import "./globals.css";
import "./listing-action-modals.css";
